name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-custom-dts:
    runs-on: [self-hosted, linux]
    defaults:
      run:
        shell: bash

    container:
      image: 'ghcr.io/cracked-machine/yocto_core:ubuntu2204'
    steps:
        # only v1 works within a self-hosted containerized actions-runner :(
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: 'true'

      - name: print env
        run: env
    
      - name: build linux 
        run: |
          set -x
          git clone https://github.com/yoctoproject/poky.git -b honister
          cd poky
          source ./oe-init-build-env
          echo "SDK_INCLUDE_NATIVESDK = 1" >> conf/local.conf
          echo "SDK_INCLUDE_PKGDATA = 1" >> conf/local.conf
          bitbake core-image-minimal
          bitbake core-image-minimal -c populate_sdk_ext

     
          
